pipeline {
    agent any

    stages {
        stage('Pull code') {
            steps {
                sh 'git clone https://github.com/Bordee2000/SDTE-Final-62070107.git'
            }
        }
        stage('Packaging') {
            steps {
                sh 'cd frontend && yarn install'
            }
        }
        stage('Run Unit test') {
            steps {
                echo 'Unit testing'
            }
        }
        stage('Run Component test') {
            steps {
                echo 'run component test'
            }
        }
        stage('Deployment') {
            steps {
                withCredentials([
                    usernamePassword(credentialsId: 'username-password-ssh', passwordVariable: 'password', usernameVariable: 'user_name'), 
                    string(credentialsId: 'frontend-host', variable: 'host_ip'), string(credentialsId: 'host_name', variable: 'host_name'), 
                    usernamePassword(credentialsId: 'SDTE-FINAL-62070107-dockerhub', passwordVariable: 'docker_password', usernameVariable: 'docker_username')]) {
                    script{
                        def remote = [:]
                        remote.name = host_name
                        remote.host = host_ip
                        remote.user = user_name
                        remote.password = password
                        remote.allowAnyHosts = true
                        
                        sshCommand remote: remote, command: "git clone https://github.com/Bordee2000/SDTE-Final-62070107.git"
                        sshCommand remote: remote, command: "docker-compose -f DTE-FINAL-62070107/docker-compose-build.yml build frontend"
                        
                        sshCommand remote: remote, command: "docker login -u $docker_username -p $docker_password"
                        sshCommand remote: remote, command: "docker push bordee2000/sdte-62070107-frontend:1.0.0"
                        sshCommand remote: remote, command: "docker image rmi -f bordee2000/sdte-62070107-frontend:1.0.0"
                        
                        sshCommand remote: remote, command: "docker pull bordee2000/sdte-62070107-frontend:1.0.0"
                        sshCommand remote: remote, command: "docker logout"
                        sshCommand remote: remote, command: "docker-compose -f SDTE-FINAL-62070107/docker-compose-deploy.yml up -d frontend"
                        sshCommand remote: remote, command: "rm -r DTE-FINAL-62070107"
                    }
                }
            }
            post{
                failure{
                    script{
                        def testing = build job: "DTE-FINAL-62070107-frontend"
                        sh '$testing.getNumber()'
                    }
                    withCredentials([gitUsernamePassword(credentialsId: 'github-DTE-FINAL-62070107-frontend', gitToolName: 'Default')]) {
                        sh 'git tag -d ' + '1.0.'+ $testing.getNumber()
                    }
                        
                }
            }
        }
        stage('API/UI testing') {
            steps {
                echo 'API/UI testing'
            }
        }
    }
}
